<?php
/*
 * File generated by netsto.com packages system
 * 
 * Below you can find current version & revision of this module
 */

$_ADDONLANG["transactions"] = "交易列表";
$_ADDONLANG["transactionsDescription"] = "在此管理Mix Pay支付订单列表";
$_ADDONLANG["user"] = "用户ID";
$_ADDONLANG["invoice"] = "订单ID";
$_ADDONLANG["amount"] = "金额";
$_ADDONLANG["ActualAmount"] = "实际支付金额";
$_ADDONLANG["PayStatus"] = "支付状态";
$_ADDONLANG["PayTime"] = "支付时间";
$_ADDONLANG["CreatedTime"] = "创建时间";
$_ADDONLANG["search"] = "搜索";
$_ADDONLANG["confirm"] = "确定";
$_ADDONLANG["cancel"] = "取消";
$_ADDONLANG["ModalTitle"] = "订单支付信息";
$_ADDONLANG["InvoiceId"] = "订单ID";
$_ADDONLANG["PayDate"] = "支付日期";
$_ADDONLANG["paymentAmount"] = "支付金额";
$_ADDONLANG["quoteSymbol"] = "支付币种";
$_ADDONLANG["status"] = "支付状态";
$_ADDONLANG["paymentAssetVersion"] = "支付网络";
$_ADDONLANG["failureCode"] = "失败代码";
$_ADDONLANG["failureReason"] = "失败原因";
$_ADDONLANG["traceId"] = "跟踪编号";
$_ADDONLANG["txid"] = "交易哈希";
$_ADDONLANG["empty"] = "暂无相关数据";
$_ADDONLANG["getSettlementAssetList"] = "获取结算货币";
$_ADDONLANG["settlementAsset"] = "结算货币ID";
$_ADDONLANG["payeeId"] = "收款人ID";
$_ADDONLANG["fineTuning"] = "微调汇率";
$_ADDONLANG["fineTuningDescription"] = "正数为加，负数为减";
$_ADDONLANG["titleTips"] = "请选择结算货币！";
$_ADDONLANG["systemTips"] = "系统提示";
$_ADDONLANG["confirmChoice"] = "确定选择";
$_ADDONLANG["symbol"] = "币种";
$_ADDONLANG["network"] = "网络";
$_ADDONLANG["accessTitleTips"] = "管理员角色权限控制";
$_ADDONLANG["accessControl"] = "权限控制";
$_ADDONLANG["administratorsRole"] = "管理员角色";
$_ADDONLANG["accessTips"] = "至少选择一个管理员角色";
$_ADDONLANG["accessMessage"] = "管理员权限控制更新成功";
$_ADDONLANG["paymentTips"] = "请先配置支付ID";
$_ADDONLANG["settlementAssetCoin"] = "结算币种";
$_ADDONLANG["global_any"] = "任意";
$_ADDONLANG["Unpaid"] = "未支付";
$_ADDONLANG["Paid"] = "已支付";
$_ADDONLANG["Failed"] = "支付失败";
$_ADDONLANG["ID"] = "ID";
$_ADDONLANG["erroroccured"] = "发生错误";
$_ADDONLANG["error"] = "错误";
$_ADDONLANG["invoicePrefix"] = "订单前缀";
$_ADDONLANG["invoicePrefixDescription"] = "当订单号不足6位时将自动拼接前缀，或者前往<a href=\"configgeneral.php#tab=7\" target=\"_blank\" style=\"color:blue;\">设置起始订单号</a>";