<?php
/*
 * File generated by netsto.com packages system
 * 
 * Below you can find current version & revision of this module
 */

$_ADDONLANG["transactions"] = "Transactions";
$_ADDONLANG["transactionsDescription"] = "Manage Mix Pay payment order list";
$_ADDONLANG["user"] = "User ID";
$_ADDONLANG["invoice"] = "Invoice ID";
$_ADDONLANG["amount"] = "Amount";
$_ADDONLANG["ActualAmount"] = "Actual Amount";
$_ADDONLANG["PayStatus"] = "Pay Status";
$_ADDONLANG["PayTime"] = "Pay Time";
$_ADDONLANG["CreatedTime"] = "Created Time";
$_ADDONLANG["search"] = "Search";
$_ADDONLANG["confirm"] = "Confirm";
$_ADDONLANG["cancel"] = "Cancel";
$_ADDONLANG["ModalTitle"] = "Order Payment Information";
$_ADDONLANG["InvoiceId"] = "Invoice Id";
$_ADDONLANG["PayDate"] = "Pay Date";
$_ADDONLANG["paymentAmount"] = "Payment Amount";
$_ADDONLANG["quoteSymbol"] = "Quote Symbol";
$_ADDONLANG["status"] = "Status";
$_ADDONLANG["paymentAssetVersion"] = "Payment Asset Version";
$_ADDONLANG["failureCode"] = "Failure Code";
$_ADDONLANG["failureReason"] = "Failure Reason";
$_ADDONLANG["traceId"] = "Trace Id";
$_ADDONLANG["txid"] = "Tx Id";
$_ADDONLANG["empty"] = "No relevant data available";
$_ADDONLANG["getSettlementAssetList"] = "Get Settlement Asset List";
$_ADDONLANG["settlementAsset"] = "Settlement Asset ID";
$_ADDONLANG["payeeId"] = "Payee Id";
$_ADDONLANG["fineTuning"] = "Fine Tuning";
$_ADDONLANG["fineTuningDescription"] = "Positive number is added, negative number is subtracted";
$_ADDONLANG["titleTips"] = "Settlement Coin list";
$_ADDONLANG["systemTips"] = "System Prompt";
$_ADDONLANG["confirmChoice"] = "Confirm Choices";
$_ADDONLANG["symbol"] = "Coin Type";
$_ADDONLANG["network"] = "Network";
$_ADDONLANG["accessTitleTips"] = "Administrator Role Access Control";
$_ADDONLANG["accessControl"] = "Access Control";
$_ADDONLANG["administratorsRole"] = "Administrator Role";
$_ADDONLANG["accessTips"] = "Select at least one administrator role";
$_ADDONLANG["accessMessage"] = "Administrator permission control update successful";
$_ADDONLANG["paymentTips"] = "Please configure the payment ID first";
$_ADDONLANG["settlementAssetCoin"] = "Settlement Asset Coin";
$_ADDONLANG["global_any"] = "Any";
$_ADDONLANG["Unpaid"] = "Unpaid";
$_ADDONLANG["Paid"] = "Paid";
$_ADDONLANG["Failed"] = "Failed";
$_ADDONLANG["ID"] = "ID";
$_ADDONLANG["erroroccured"] = "An Error Occurred";
$_ADDONLANG["error"] = "Error";
$_ADDONLANG["invoicePrefix"] = "Invoice Prefix";
$_ADDONLANG["invoicePrefixDescription"] = "When the invoice# is less than 6 chars, the prefix will be auto concatenated, or go to <a href=\"configgeneral.php#tab=7\" target=\"_blank\" style=\"color:blue;\">Set Invoice Starting #</a>";