<?php
/*
 * File generated by netsto.com packages system
 * 
 * Below you can find current version & revision of this module
 */

error_reporting(0);     //Temporarily disable error display
ini_set("display_errors",0);
use WHMCS\Database\Capsule;
if (!defined("WHMCS")) {
    exit("This file cannot be accessed directly");
}

// module config
function mixpay_config(){
    global $aInt;
    global $_ADDONLANG;
    $addonlang = $_ADDONLANG;
    $module = "mixpay";
    $addonlangfile = ROOTDIR . "/modules/addons/" . $module . "/lang/" . $aInt->language . ".php";  // load language file
    if (file_exists($addonlangfile)) {
        require $addonlangfile;
    }
 
    $_ADDONLANG = array_merge($addonlang, $_ADDONLANG);

    $configarray = array(
        "name" => 'MixPay '.$_ADDONLANG["transactions"],
	    "description" => $_ADDONLANG["transactionsDescription"],
        'author' => 'Netsto.com',
	    "version" => "1.0",
        "language" => "chinese"
    );
    return $configarray;
}

//create table
function mixpay_activate() {
    mysql_query("CREATE TABLE `mixpay_orders` (
		`id` int(11) NOT NULL AUTO_INCREMENT,
		`userId` int(11) NOT NULL COMMENT 'User ID',
		`InvoiceId` varchar(255) NOT NULL COMMENT 'Invoice ID',
		`orderId` varchar(255) NOT NULL COMMENT 'Order ID',
		`payeeId` varchar(255) DEFAULT NULL COMMENT 'payeeId',
		`settlementAssetId` varchar(255) NULL DEFAULT NULL COMMENT 'settlementAssetId',
		`quoteAssetId` varchar(255) NULL DEFAULT NULL COMMENT 'quoteAssetId',
		`amount` varchar(255) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Amount',
		`ActualAmount` varchar(255) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Actual Amount',
        `quoteSymbol` varchar(255) NULL DEFAULT NULL COMMENT 'Quote Symbol',
		`status` varchar(255) NOT NULL DEFAULT 'Unpaid' COMMENT 'Payment Status',
		`time` datetime NULL DEFAULT NULL COMMENT 'Payment Time',
        `remarks` text NULL DEFAULT NULL COMMENT 'Remarks',
		`created_at` datetime NULL DEFAULT NULL COMMENT 'Created Time',
		`updated_at` datetime NULL DEFAULT NULL COMMENT 'Updated Time',
		PRIMARY KEY (`id`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;");
}

//deactivate module
function mixpay_deactivate() {}

//output module
function mixpay_output($vars){
    global $CONFIG;

    global $aInt;
    if(!function_exists("getGatewayVariables")){
        include_once ROOTDIR . "/includes/gatewayfunctions.php";
    }
    $gatewayparams = getGatewayVariables("mixpay");
    $payeeId = $gatewayparams["payeeId"];
    $systemUrl = $CONFIG['SystemURL'];
    $LANG = $vars["_lang"];

    if (!defined("WHMCS") && empty($_SESSION['adminid'])) {
        ob_clean();
        die("This file cannot be accessed directly");
    }

    require_once($_SERVER['DOCUMENT_ROOT']."/includes/gatewayfunctions.php");
    require_once($_SERVER['DOCUMENT_ROOT']."/includes/invoicefunctions.php");
    
    $payeeId = get_query_val("tblpaymentgateways", "value", ["gateway" => "mixpay","setting" => "payeeId"]); // payeeId

    // ajax request
    if (isset($_SERVER["HTTP_X_REQUESTED_WITH"]) && strtolower($_SERVER["HTTP_X_REQUESTED_WITH"]) == "xmlhttprequest") {
        $action = $_POST["action"];
        switch ($action) {
            // get payment info
            case "getPayInfo":
                $orderId = get_query_val("mixpay_orders","orderId",["InvoiceId" => $_POST["InvoiceId"]]);
                $params = [
                    "method" => "GET",
                    "path" => "payments_result?orderId=".$orderId."&payeeId=".$payeeId // get payment info
                ];
                try{
                    $result = mixpay_sendRequest($params);
                    $result["data"]["date"] = ($result["data"]["date"]) ? date("Y-m-d H:i:s", $result["data"]["date"]) : "";
                    $result["data"]["txidUrl"] = $systemUrl."/?m=mixpay&url=" . $result["data"]["blockExplorerUrl"];
                    exit(json_encode($result, JSON_UNESCAPED_UNICODE));
                }catch(Exception $e){
                    exit(json_encode(["success" => false,"message" => AdminLang::trans("global.error").": ".$e->getMessage()]));
                }
                break;
            // get settlement assets
            case "settlement_assets":
                $lists = [];
                $params = [
                    "method" => "GET",
                    "path" => "setting/settlement_assets" // get settlement assets
                ];
                try{
                $result = mixpay_sendRequest($params);
                    foreach($result["data"] as $key => $value){
                        $lists[$value["symbol"]][] = [
                            "assetId" => $value["assetId"],
                            "network" => $value["network"]
                        ];
                    }
                    exit(json_encode(["lists" => $lists],JSON_UNESCAPED_UNICODE));
                }catch(Exception $e){
                    exit(json_encode(["success" => false,"message" => AdminLang::trans("global.error").": ".$e->getMessage()]));
                }
                break;
            // access control
            case "access_control":
                $lists = [];
                $accessValue = get_query_val("tbladdonmodules","value",["module" => "mixpay","setting" => "access"]);
                $access = explode(",",$accessValue);
                $res = select_query("tbladminroles","*",[]);
                while($db = mysql_fetch_assoc($res)){
                    $db["checked"] = (in_array($db["id"],$access)) ? "checked" : "";
                    $lists[] = $db;
                }
                exit(json_encode(["lists" => $lists],JSON_UNESCAPED_UNICODE));
                break;
            // update access control
            case "access_add":
                $where = [
                    "module" => "mixpay",
                    "setting" => "access"
                ];
                $array = [
                    "value" => implode(",",$_POST["access"])
                ];
                update_query("tbladdonmodules",$array,$where);
                exit(json_encode(["success" => true,"message" => $LANG["accessMessage"]],JSON_UNESCAPED_UNICODE));
                break;
        }
    }
    if(!$gatewayparams["payeeId"]){
        exit('<script type="text/javascript">
            alert("'.$LANG["paymentTips"].'");
            setTimeout(function(){
                location.href="configgateways.php?manage=1#m_mixpay";
            },100)
        </script>');
    }

    // get search params
    $userId = App::getFromRequest("userId");
    $searchInvoiceId = App::getFromRequest("InvoiceId");
    $searchCreatedAt = App::getFromRequest("created_at");
    $searchStatus = App::getFromRequest("status");

    // init table
    $aInt->sortableTableInit("id", "DESC");
    
    // build query - using Laravel query builder
    $query = WHMCS\Database\Capsule::table("mixpay_orders");
    
    // apply search filter
    if ($userId) {
        $query->where("userId", $userId);
    }
    if ($searchInvoiceId) {
        $query->where("InvoiceId", $searchInvoiceId);
    }
    if ($searchStatus && $searchStatus != "") {
        $query->where("status", $searchStatus);
    }
    
    // handle date range search
    if ($searchCreatedAt) {
        $date = WHMCS\Carbon::parseDateRangeValue($searchCreatedAt);
        $startDate = $date["from"];
        $endDate = $date["to"];
        $query->whereBetween("created_at", [$startDate->toDateTimeString(), $endDate->toDateTimeString()]);
    }
    
    // get total records
    global $numrows;
    $numrows = $query->count();
    
    // get data
    $query->orderBy("id", "DESC");
    $tabledata = array();
    
    foreach ($query->get() as $data) {
        $data = (array) $data;
        $id = $data["id"];
        $displayUserId = $data["userId"];
        $InvoiceId = '<a href="javascript:getPayInfo('.$data["InvoiceId"].')" style="color: #0af;">' . $data["InvoiceId"] . '</a>';
        $amount = $data["amount"];
        $ActualAmount = $data["ActualAmount"];
        $quoteSymbol = $data["quoteSymbol"];
        $status = $data["status"];
        $time = ($data["time"]) ? $data["time"] : "";
        $displayCreatedAt = fromMySQLDate($data["created_at"], true, true);
        if (substr($displayCreatedAt, 0, 10) == "0000-00-00") {
            $displayCreatedAt = "-";
        }
        
        $tabledata[] = array($id, $displayUserId, $InvoiceId, $amount, $ActualAmount, $quoteSymbol, $status, $time, $displayCreatedAt);
    }
    
    // start output content
    ob_start();
    
    // using beginAdminTabs to create collapsible search filter
    echo $aInt->beginAdminTabs([AdminLang::trans("global.searchfilter")]);
    
    // output search form
    echo '<form method="post" action="addonmodules.php?module=mixpay">';
    echo '<input type="hidden" name="filter" value="true">';
    echo '<table class="form" width="100%" border="0" cellspacing="2" cellpadding="3">';
    echo '<tr>';
    echo '<td width="15%" class="fieldlabel">'.$LANG["user"].'</td>';
    echo '<td class="fieldarea">';
    echo '<input type="text" name="userId" class="form-control input-400" value="'.$userId.'">';
    echo '</td>';
    echo '<td width="15%" class="fieldlabel">'.$LANG["invoice"].'</td>';
    echo '<td class="fieldarea">';
    echo '<input type="text" name="InvoiceId" class="form-control input-400" value="'.$searchInvoiceId.'">';
    echo '</td>';
    echo '</tr>';
    echo '<tr>';
    echo '<td class="fieldlabel">'.$LANG["CreatedTime"].'</td>';
    echo '<td class="fieldarea">';
    echo '<div class="form-group date-picker-prepend-icon">';
    echo '<label for="inputCreatedAt" class="field-icon">';
    echo '<i class="fal fa-calendar-alt"></i>';
    echo '</label>';
    echo '<input id="inputCreatedAt" type="text" name="created_at" value="'.$searchCreatedAt.'" class="form-control date-picker-search" data-opens="left">';
    echo '</div>';
    echo '</td>';
    echo '<td class="fieldlabel">'.$LANG["PayStatus"].'</td>';
    echo '<td class="fieldarea">';
    echo '<select name="status" class="form-control select-inline">';
    echo '<option value=""'.($searchStatus == "" ? " selected" : "").'>'.$LANG["global_any"].'</option>';
    echo '<option value="Unpaid"'.($searchStatus == "Unpaid" ? " selected" : "").'>'.$LANG["Unpaid"].'</option>';
    echo '<option value="Paid"'.($searchStatus == "Paid" ? " selected" : "").'>'.$LANG["Paid"].'</option>';
    echo '<option value="Failed"'.($searchStatus == "Failed" ? " selected" : "").'>'.$LANG["Failed"].'</option>';
    echo '</select>';
    echo '</td>';
    echo '</tr>';
    echo '</table>';
    echo '<div class="btn-container">';
    echo '<input type="submit" value="'.$LANG["search"].'" class="btn btn-primary">';
    echo '</div>';
    echo '</form>';
    
    // end tab
    echo $aInt->endAdminTabs();
    echo '<br />';
    
    // output table - sortableTable will automatically display record count and pagination information
    echo $aInt->sortableTable(array(
        array("id", $LANG["ID"], "50"),
        array("userId", $LANG["user"], "100"),
        array("InvoiceId", $LANG["invoice"], "100"),
        array("amount", $LANG["amount"], "100"),
        array("ActualAmount", $LANG["ActualAmount"], "100"),
        array("quoteSymbol", $LANG["quoteSymbol"], "100"),
        array("status", $LANG["PayStatus"], "100"),
        array("time", $LANG["PayTime"], "160"),
        array("created_at", $LANG["CreatedTime"], "160")
    ), $tabledata);
    
    // popup layer
    echo '<!-- popup layer -->
    <div class="modal fade modal-remove-item" id="modalTips" tabindex="-1" role="dialog" data-backdrop="static">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">
                        <i class="fas fa-info-circle fa-fw" id="titleI"></i>
                        <span id="InvoiceId"></span>
                        <span id="ModalTitle"># '.$LANG["ModalTitle"].'</span>
                        <span id="erroroccured" style="display:none"># '.$LANG["erroroccured"].'</span>
                    </h4>
                </div>
                <div class="modal-body" style="text-align:left" id="tipsContent"></div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">'.$LANG["confirm"].'</button>
                </div>
            </div>
        </div>
    </div>';
    
    // JavaScript code
    echo '<script type="text/javascript">
    var LANG = {
        empty:"'.addslashes($LANG['empty']).'",
        InvoiceId:"'.addslashes($LANG['InvoiceId']).'",
        PayDate:"'.addslashes($LANG['PayDate']).'",
        paymentAmount:"'.addslashes($LANG['paymentAmount']).'",
        quoteSymbol:"'.addslashes($LANG['quoteSymbol']).'",
        status:"'.addslashes($LANG['status']).'",
        paymentAssetVersion:"'.addslashes($LANG['paymentAssetVersion']).'",
        failureCode:"'.addslashes($LANG['failureCode']).'",
        failureReason:"'.addslashes($LANG['failureReason']).'",
        traceId:"'.addslashes($LANG['traceId']).'",
        txid:"'.addslashes($LANG['txid']).'",
        ModalTitle:"'.addslashes($LANG["ModalTitle"]).'",
        erroroccured:"'.addslashes(AdminLang::trans("global.error")).'"
    };
    </script>';
    
    // include JavaScript file
    echo '<script type="text/javascript" src="/modules/addons/mixpay/mixpay.js"></script>';
    
    $content = ob_get_contents();
    ob_end_clean();
    
    echo $content;
}
function mixpay_clientarea($vars){
    // redirect URL, prevent tracking
    $jump_url = $_GET["url"];
    if(!empty($jump_url)){
        $scheme = parse_url($jump_url)["scheme"];
        if(empty($scheme)){
            exit($jump_url."不是一个有效的URL");
        }
        exit(header("Location: {$jump_url}"));
    }
}

// Send request
function mixpay_sendRequest($params){
    $url = "https://api.mixpay.me/v1/".$params["path"];
    $options = [
        CURLOPT_URL => $url,
        CURLOPT_HTTPHEADER => ["content-type: application/json"],
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_SSL_VERIFYPEER => false,
        CURLOPT_SSL_VERIFYHOST => false,
        CURLOPT_CUSTOMREQUEST => strtoupper($params["method"]),
        CURLOPT_POSTFIELDS => json_encode($params["request"]),
        CURLOPT_CONNECTTIMEOUT => 30,
        CURLOPT_TIMEOUT => 30,
    ];

    $ch = curl_init();
    curl_setopt_array($ch, $options);
    $response = curl_exec($ch);

    if (curl_errno($ch)) {
        $error_message = "CURL Error: " . curl_error($ch);
        curl_close($ch);
        throw new Exception($error_message);
    }

    curl_close($ch);
    $response = json_decode($response, true);

    if (!$response || isset($response["success"]) && $response["success"] === false) {
        $error_message = "API Error: " . ($response["message"] ?? "Unknown error");
        throw new Exception($error_message);
    }

    return $response;
}