<?php
/*
 * File generated by netsto.com packages system
 * 
 * Below you can find current version & revision of this module
 */

// MixPay payment gateway configuration
function mixpay_config()
{
    global $gatewayModuleName;  // Global variable
    $module = $gatewayModuleName;   // Get module name
    global $aInt;
    $addonlangfile = ROOTDIR . "/modules/addons/" . $module . "/lang/" . $aInt->language . ".php";  // Load language file
    if (file_exists($addonlangfile)) {
        require $addonlangfile;
    }

    mysql_query("CREATE TABLE `mixpay_orders` (
		`id` int(11) NOT NULL AUTO_INCREMENT,
		`userId` int(11) NOT NULL COMMENT 'User ID',
		`InvoiceId` varchar(255) NOT NULL COMMENT 'System invoice ID',
		`orderId` varchar(255) NOT NULL COMMENT 'Payment invoice ID',
		`payeeId` varchar(255) DEFAULT NULL COMMENT 'payeeId',
		`settlementAssetId` varchar(255) NULL DEFAULT NULL COMMENT 'settlementAssetId',
		`quoteAssetId` varchar(255) NULL DEFAULT NULL COMMENT 'quoteAssetId',
		`amount` varchar(255) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Amount',
		`ActualAmount` varchar(255) COLLATE utf8_unicode_ci NOT NULL COMMENT 'Actual payment amount',
        `quoteSymbol` varchar(255) NULL DEFAULT NULL COMMENT 'Payment currency',
		`status` varchar(255) NOT NULL DEFAULT 'Unpaid' COMMENT 'Payment status',
		`time` datetime NULL DEFAULT NULL COMMENT 'Payment time',
        `remarks` text NULL DEFAULT NULL COMMENT 'Remarks',
		`created_at` datetime NULL DEFAULT NULL COMMENT 'Created time',
		`updated_at` datetime NULL DEFAULT NULL COMMENT 'Updated time',
		PRIMARY KEY (`id`)
	) ENGINE=InnoDB DEFAULT CHARSET=utf8;");
    $modalTips = '<div class="modal fade modal-remove-item" id="modalTips" tabindex="-1" role="dialog" data-backdrop="static">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">
                        <i class="fas fa-info-circle fa-fw"></i>
                        <span id="titleTips">'.$_ADDONLANG["titleTips"].'</span>
                    </h4>
                </div>
                <div class="modal-body" style="display:flex">
                    <div id="symoblTitle" style="width:20%;margin:15px">'.$_ADDONLANG["symbol"].'</div>
                    <div id="symbolContent" style="display:flex;flex-wrap:wrap;"></div>
                </div>
                <hr style="margin:0 15px">
                <div class="modal-body" id="tipsNetwork" style="display:flex;padding:0;">
                    <div style="width:20%;margin:30px 15px">'.$_ADDONLANG["network"].'</div>
                    <div id="tipsContent" style="padding:15px;"></div>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-default" id="btn" data-dismiss="modal" onclick="ConfirmAssetId()">'.$_ADDONLANG["confirm"].'</button>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade modal-remove-item" id="modalTipsMessage" tabindex="-1" role="dialog" data-backdrop="static">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">
                        <i class="fas fa-info-circle fa-fw"></i>
                        <span>'.$_ADDONLANG["systemTips"].'</span>
                    </h4>
                </div>
                <div class="modal-body text-center" id="infoTips"></div>
                <div class="modal-footer" id="infoBtn"></div>
            </div>
        </div>
    </div>';
    $configarray = [
        "FriendlyName" => ["Type" => "System", "Value" => "MixPay"],
        "payeeId" => ["FriendlyName" => $_ADDONLANG["payeeId"], "Type" => "text", "Size" => "32"],
        "settlementAssetId" => [
            "FriendlyName" => $_ADDONLANG["settlementAsset"],
            "Type" => "text",
            "Size" => "32",
            "Description" => '<button class="btn btn-info btn-sm" onclick="fetchSettlementAssets()"><i class="fas fa-list" style="padding-right:5px"></i>'.$_ADDONLANG["getSettlementAssetList"].'</button>'.$modalTips
        ],
        "accessControl" => [
            "FriendlyName" => $_ADDONLANG["accessControl"],
            "Type" => "html",
            "Size" => "32",
            "Description" => '<button class="btn btn-warning btn-sm" onclick="accessControl()" style="margin-left"><i class="fas fa-users-cog" style="padding-right:5px"></i>'.$_ADDONLANG["accessControl"].'</button>'
        ],
        "invoicePrefix" => [
            "FriendlyName" => $_ADDONLANG["invoicePrefix"],
            "Type" => "text",
            "Size" => "10",
            "Default" => "mixpay",
            "Description" => $_ADDONLANG["invoicePrefixDescription"]
        ],
        "FineTuning" => ["FriendlyName" => $_ADDONLANG["fineTuning"], "Type" => "text", "Size" => "32", "Default" => "0.0001", "Description" => $_ADDONLANG["fineTuningDescription"]]
    ];
    if ($module != 'mixpay' && (isset($_REQUEST['gateway']) && $_REQUEST['gateway'] !== 'mixpay') || isset($_REQUEST['action'])) {
        return $configarray;
    }
    // Optimize judgment logic, return configuration only when the request is not mixpay or the operation is deactivate/activate
    if ($module != 'mixpay' && (isset($_REQUEST['gateway']) && $_REQUEST['gateway'] !== 'mixpay') || (isset($_REQUEST['action']) && in_array($_REQUEST['action'], ['deactivate', 'activate']))) {
        return $configarray;
    }
    echo '<script type="text/javascript">
        var lists = [];
		function fetchSettlementAssets() {
            event.preventDefault(); // Prevent form submission
            var url = "addonmodules.php?module=mixpay";
            var data = {
                action:"settlement_assets"
            };
            $.post(url,data,function(res){
                lists = res.lists;
                var txt = "";
                var symbolType = "USDT";
                $.each(res.lists,function(index,item){
                    if($("input[name=\"field[settlementAssetId]\"]").val()){
                        $.each(item,function(key,value){
                            if(value.assetId === $("input[name=\"field[settlementAssetId]\"]").val()) symbolType = index;
                        })
                    }
                    if(index === symbolType){
                        var symbolChecked = "checked";
                        var borderColor = "#3c7ee5";
                    }else{
                        var symbolChecked = "";
                        var borderColor = "#dcdfe6";
                    }
                    txt += "<div class=\"col-sm-6 text-center\" style=\"width:auto;line-height:30px;margin:10px;border: 1px solid "+borderColor+"\">\
                        <label class=\"radio-inline\"><input type=\"radio\" name=\"symbol\" value=\""+index+"\" onclick=\"ChoiceSymbol()\" "+symbolChecked+" style=\"margin-top:8px\"> <span>"+index+"</span></label>\
                    </div>";
                })
                $("#titleTips").html("'.$_ADDONLANG["titleTips"].'");
                $("#symoblTitle").html("'.$_ADDONLANG["symbol"].'");
                $("#symbolContent").html(txt);
                $("#btn").attr("onclick","ConfirmAssetId()");
                $("#tipsNetwork").show();
                ChoiceSymbol();
                jQuery("#modalTips").modal("show");
            },"json")
		}
        function ChoiceSymbol(){
            var txt = "";
            $("#symbolContent").find("div").css("border-color","#dcdfe6");
            $("input[name=\"symbol\"]:checked").parent().parent().css("border-color","#3c7ee5");
            $.each(lists[$("input[name=\"symbol\"]:checked").val()],function(index,item){
                if(!$("input[name=\"field[settlementAssetId]\"]").val()){
                    if(item.assetId === "94213408-4ee7-3150-a9c4-9c5cce421c78"){
                        var assetIdChecked = "checked";
                        var borderColor = "#3c7ee5";
                    }
                }else{
                    if(item.assetId === $("input[name=\"field[settlementAssetId]\"]").val()){
                        var assetIdChecked = "checked";
                        var borderColor = "#3c7ee5";
                    }else{
                        var assetIdChecked = "";
                        var borderColor = "#dcdfe6";
                    }
                }
                txt += "<div class=\"col-sm-6 text-center\" style=\"width:auto;line-height:30px;margin:10px;border: 1px solid "+borderColor+"\">\
                    <label class=\"radio-inline\"><input type=\"radio\" name=\"assetId\" value=\""+item.assetId+"\" onclick=\"ChoiceAssetId()\" "+assetIdChecked+" style=\"margin-top:8px\"> <span>"+item.network+"</span></label>\
                </div>";
            })
            $("#tipsContent").html(txt);
        }
        function ChoiceAssetId(){
            $("#tipsContent").find("div").css("border-color","#dcdfe6");
            $("input[name=\"assetId\"]:checked").parent().parent().css("border-color","#3c7ee5");
        }
        function ConfirmAssetId(){
            event.preventDefault(); // Prevent form submission
            if(!$("input[name=\"assetId\"]:checked").length){
                $("#infoTips").html("'.$_ADDONLANG["titleTips"].'");
                $("#infoBtn").html("<button class=\"btn btn-default\" data-dismiss=\"modal\">'.$_ADDONLANG["confirm"].'</button>");
                jQuery("#modalTipsMessage").modal("show");
                event.stopPropagation();
                return false;
            }
            // $("#infoTips").html("'.$_ADDONLANG["confirmChoice"].' “"+$("input[name=\"symbol\"]:checked").val()+" "+$("input[name=\"assetId\"]:checked").parent().find("span").html()+"” '.$_ADDONLANG["settlementAsset"].'？");
            // $("#infoBtn").html("<button class=\"btn btn-danger\" data-dismiss=\"modal\">'.$_ADDONLANG["cancel"].'</button><button class=\"btn btn-default\" data-dismiss=\"modal\" onclick=\"ConfirmSettlementAssetId()\">'.$_ADDONLANG["confirm"].'</button>");
            // jQuery("#modalTipsMessage").modal("show");
            ConfirmSettlementAssetId();
        }
        function ConfirmSettlementAssetId(){
            $("input[name=\"field[settlementAssetId]\"]").val($("input[name=\"assetId\"]:checked").val());
        }
        function accessControl(){
            event.preventDefault(); // Prevent form submission
            var url = "addonmodules.php?module=mixpay";
            var data = {
                action:"access_control"
            };
            $.post(url,data,function(res){
                var txt = "";
                $.each(res.lists,function(index,item){
                    var borderColor = (item.checked === "checked") ? "#3c7ee5" : "#dcdfe6";
                    txt += "<div class=\"col-sm-6 text-center\" style=\"width:auto;line-height:30px;margin:10px;border: 1px solid "+borderColor+"\">\
                        <label class=\"checkbox-inline\"><input type=\"checkbox\" name=\"access\" value=\""+item.id+"\" onchange=\"ChoiceAccess()\" "+item.checked+" style=\"margin-top:8px\"> <span>"+item.name+"</span></label>\
                    </div>";
                })
                $("#titleTips").html("'.$_ADDONLANG["accessTitleTips"].'");
                $("#symoblTitle").html("'.$_ADDONLANG["administratorsRole"].'");
                $("#symbolContent").html(txt);
                $("#btn").attr("onclick","ConfirmAdminstrators()");
                $("#tipsNetwork").hide();
                jQuery("#modalTips").modal("show");
            },"json")
        }
        function ChoiceAccess(){
            $.each($("input[name=\"access\"]"),function(index,item){
                var borderColor = (item.checked) ? "#3c7ee5" : "#dcdfe6";
                $(this).parent().parent().css("border-color",borderColor);
            })
        }
        function ConfirmAdminstrators(){
            event.preventDefault(); // Prevent form submission
            if(!$("input[name=\"access\"]:checked").length){
                $("#infoTips").html("'.$_ADDONLANG["accessTips"].'");
                $("#infoBtn").html("<button class=\"btn btn-default\" data-dismiss=\"modal\">'.$_ADDONLANG["confirm"].'</button>");
                jQuery("#modalTipsMessage").modal("show");
                event.stopPropagation();
                return false;
            }
            var access = [];
            $.each($("input[name=\"access\"]:checked"),function(index,item){
                access.push(item.value)
            })
            var url = "addonmodules.php?module=mixpay";
            var data = {
                action:"access_add",
                access:access
            };
            $.post(url,data,function(res){
                $("#infoTips").html(res.message);
                $("#infoBtn").html("<button class=\"btn btn-default\" data-dismiss=\"modal\">'.$_ADDONLANG["confirm"].'</button>");
                jQuery("#modalTipsMessage").modal("show");
                event.stopPropagation();
                return false;
            },"json")
        }
	</script>';
   
    if(isset($_REQUEST['activated']) && $_REQUEST['activated'] == $module){
        $params["addon_name"] = "MixPay ".$_ADDONLANG["transactions"];      // Plugin name
        mixpay_autoactivate($params);      // Automatically activate associated modules
    }
    return $configarray;
}

// Automatically activate associated modules
function mixpay_autoactivate(array $params)
{
    global $whmcs;
    $addon_name = $params["addon_name"];
    $module = 'mixpay';

    mixpay_modifyModules($module);  // Activate module
    // Check if version record exists
    $versionExists = get_query_val("tbladdonmodules", "id", ["module" => $module, "setting" => "version"]);
    if (!$versionExists) {
        insert_query("tbladdonmodules", [
            "module" => $module,
            "setting" => "version",
            "value" => "1.0"
        ]);
    }
    // Check if access record exists
    $accessExists = get_query_val("tbladdonmodules", "id", ["module" => $module, "setting" => "access"]);
    $accessArray = [];
    $res = select_query("tbladminroles", "*", []);
    $modulesperms = safe_unserialize($whmcs->get_config("AddonModulesPerms"));      // Get module permissions
    while ($db = mysql_fetch_assoc($res)) {
        $accessArray[] = $db["id"];
        $modulesperms[$db["id"]][$module] = $addon_name;
    }
    $whmcs->set_config("AddonModulesPerms", safe_serialize($modulesperms));     // Set module permissions
    $accessList = implode(",", $accessArray);
    if ($accessExists) {
        update_query("tbladdonmodules", ["value" => $accessList], ["module" => $module, "setting" => "access"]);
    } else {
        // If it does not exist, insert
        insert_query("tbladdonmodules", [
            "module" => $module,
            "setting" => "access",
            "value" => $accessList
        ]);
    }
}

// Modify module status
function mixpay_modifyModules($module, $action = "add"){
    if(empty($module)){
        return false;
    }
    global $CONFIG;
    global $whmcs;
    global $GatewayValues;
    $moduleName = $GatewayValues[$module]["name"];      // Module name
    $activemodules = $CONFIG["ActiveAddonModules"];
    $activemodules = explode(",", $activemodules);
    if($action == "add"){
        $activemodules[] = $module;
        sort($activemodules);
        $whmcs->set_config("ActiveAddonModules", implode(",", $activemodules));
        $action = "Activated";
    }else{
        foreach ($activemodules as $k => $val) {
            if ($val == $module) {
                unset($activemodules[$k]);
            }
        }
        sort($activemodules);
        $whmcs->set_config("ActiveAddonModules", implode(",", $activemodules));
        $action = "Deactivated";
    }
    logAdminActivity("Addon Module " . $action . " - " . $moduleName);
    return true;
}

// Automatically deactivate modules
function mixpay_deactivate(array $params){
    $module = 'mixpay';
    global $whmcs;
    mixpay_modifyModules($module, $action = "remove");  // Delete module
    $modulesperms = safe_unserialize($whmcs->get_config("AddonModulesPerms"));      // Get module permissions
    if(!empty($modulesperms) && is_array($modulesperms)){
        foreach ($modulesperms as $key => $val) {
            if($val[$module]){
                unset($modulesperms[$key][$module]);
            }
        }
        $whmcs->set_config("AddonModulesPerms", safe_serialize($modulesperms)); 
    }
    delete_query("tbladdonmodules", ["module" => "mixpay"]);    // Delete module record
}

function mixpay_link($params)
{
    global $CONFIG;
    $clientURL = $CONFIG['SystemURL'].'/clientarea.php';
    $referrer = $_SERVER['HTTP_REFERER'] ?? $clientURL;
    $actual = $params["amount"]; // input amount
    $currency = getCurrency($_SESSION["uid"]); // current user currency rate
    $params["amount"] = sprintf("%.2f", ($params["amount"] / ($currency["rate"] + (float)$params["FineTuning"]))); // convert rate

    $invoicePrefix = empty($params["invoicePrefix"]) ? "mixpay" : $params["invoicePrefix"];
    if(strlen($params["invoiceid"]) < 6){
        $invoiceid = $invoicePrefix . $params["invoiceid"];
    }else{
        //if invoicePrefix is not mixpay, the user has customized the prefix
        if($invoicePrefix != "mixpay"){
            $invoiceid = $invoicePrefix . $params["invoiceid"];
        }else{
            $invoiceid = $params["invoiceid"];
        }
    }
    try {
        $requestData = [
            "one_time_payment" => [
                "uri" => "/one_time_payment",
                "request" => [
                    "payeeId" => $params["payeeId"],
                    "orderId" => (string)$invoiceid,
                    "settlementAssetId" => $params["settlementAssetId"],
                    "quoteAmount" => $params["amount"],
                    "quoteAssetId" => $params["settlementAssetId"],
                    "isChain" => true,
                    "callbackUrl" => $CONFIG['SystemURL']."/modules/gateways/callback/mixpay.php",
                    "returnTo" => $referrer  // Jump along the way
                ],
                "method" => "POST"
            ],
            "settlement_assets" => [
                "uri" => "/setting/settlement_assets",
                "method" => "GET"
            ]
        ];
        $multiResponse = mixpay_multiSendRequest($requestData);
        $response = $multiResponse["one_time_payment"];
        $settlement_assets = $multiResponse["settlement_assets"]["data"];  // Settlement currency list
    } catch (Exception $e) {
        return $e->getMessage();
    }
    $quoteSymbol = "";
    foreach($settlement_assets as $index => $item){
        if($item["assetId"] == $params["settlementAssetId"]) $quoteSymbol = $item["symbol"];
    }
    $data = [
        "userId" => $_SESSION["uid"],
        "InvoiceId" => $params["invoiceid"],
        "orderId" => $response["data"]["info"]["orderId"],
        "payeeId" => $params["payeeId"],
        "settlementAssetId" => $params["settlementAssetId"],
        "quoteAssetId" => $params["settlementAssetId"],
        "amount" => $actual,
        "ActualAmount" => $params["amount"],
        "quoteSymbol" => $quoteSymbol,
        "created_at" => date("Y-m-d H:i:s")
    ];
    $gid = get_query_val("mixpay_orders", "id", ["InvoiceId" => $params["invoiceid"],"orderId" => $response["data"]["info"]["orderId"],"destination" => $response["data"]["info"]["destination"]]);
    if (!$gid) {
        $sid = insert_query("mixpay_orders", $data);
    }
    exit(header("Location:https://mixpay.me/code/".$response["data"]["code"]));
}

// Get settlement currency list
function mixpay_getSettlementAssetList()
{
    try {
        $response = mixpay_sendRequest("/setting/settlement_assets");
    } catch (Exception $e) {
        return $e->getMessage();
    }
    return $response;
}


// Multi-threaded request
function mixpay_multiSendRequest($requestData)
{
    $requests = [];
    foreach ($requestData as $key => $value) {
        $requests[$key] = [
            "url" => "https://api.mixpay.me/v1".$value["uri"],
            "request" => is_array($value["request"]) ? json_encode($value["request"]) : $value["request"],
            "method" => $value["method"]
        ];
    }

    $conn = array();
    $res = array();
    $mh = curl_multi_init();

    foreach ($requests as $k => $item) {
        $conn[$k] = curl_init();
        curl_setopt($conn[$k], CURLOPT_URL, $item['url']);
        curl_setopt($conn[$k], CURLOPT_HEADER, false);
        curl_setopt($conn[$k], CURLOPT_HTTPHEADER, ['content-type: application/json']);
        curl_setopt($conn[$k], CURLOPT_RETURNTRANSFER, true);
        curl_setopt($conn[$k], CURLOPT_TIMEOUT, 10);
        curl_setopt($conn[$k], CURLOPT_SSL_VERIFYPEER, false);
        curl_setopt($conn[$k], CURLOPT_SSL_VERIFYHOST, false);
        curl_setopt($conn[$k], CURLOPT_USERAGENT, "Mozilla/5.0 (X11; CentOS; Linux x86_64) Gecko/20100101 Firefox/101.0");
        curl_setopt($conn[$k], CURLOPT_ENCODING, 'gzip,deflate');
        if (strtolower($item['method']) == 'post') {
            curl_setopt($conn[$k], CURLOPT_POST, true);
            curl_setopt($conn[$k], CURLOPT_POSTFIELDS, $item['request']);
        }
        curl_setopt($conn[$k], CURLOPT_FOLLOWLOCATION, 1);
        curl_multi_add_handle($mh, $conn[$k]);
    }

    $active = null;
    do {
        $mrc = curl_multi_exec($mh, $active);
        if ($mrc != CURLM_OK && $mrc != CURLM_CALL_MULTI_PERFORM) {
            throw new Exception("Multi-threaded execution error: " . curl_multi_strerror($mrc));
        }
    } while ($mrc == CURLM_CALL_MULTI_PERFORM);

    while ($active && $mrc == CURLM_OK) {
        if (curl_multi_select($mh) != -1) {
            do {
                $mrc = curl_multi_exec($mh, $active);
                if ($mrc != CURLM_OK && $mrc != CURLM_CALL_MULTI_PERFORM) {
                    throw new Exception("Multi-threaded execution error: " . curl_multi_strerror($mrc));
                }
            } while ($mrc == CURLM_CALL_MULTI_PERFORM);
        }
    }

    $errorMessages = [];
    foreach ($requests as $k => $item) {
        $res[$k] = json_decode(curl_multi_getcontent($conn[$k]), true);
        if (curl_errno($conn[$k])) {
            $errorMessages[] = 'Curl error: ' . curl_error($conn[$k]);
        }
        curl_multi_remove_handle($mh, $conn[$k]);
        curl_close($conn[$k]);
    }

    curl_multi_close($mh);

    if (!empty($errorMessages)) {
        throw new Exception("Error occurred during request: " . implode("; ", $errorMessages));
    }

    return $res;
}

// Single-threaded request API
function mixpay_sendRequest2($uri, $request = [], $method = "GET")
{
    //$params = getGatewayVariables("mixpay");

    $request_str = is_array($request) ? json_encode($request) : $request;
    $url = "https://api.mixpay.me/v1".$uri;

    $ch = curl_init();
    curl_setopt_array($ch, [
        CURLOPT_URL => $url,
        CURLOPT_HTTPHEADER => ['content-type: application/json'],
        CURLOPT_CUSTOMREQUEST => $method,
        CURLOPT_TIMEOUT => 50,
        CURLOPT_POSTFIELDS => $request_str,
        CURLOPT_RETURNTRANSFER => 1,
        CURLOPT_SSL_VERIFYPEER => false,
        CURLOPT_SSL_VERIFYHOST => false,
        CURLOPT_ENCODING => "gzip,deflate",
        CURLOPT_USERAGENT => "Mozilla/5.0 (X11; CentOS; Linux x86_64) Gecko/20100101 Firefox/101.0"
    ]);

    $response = curl_exec($ch);
    if (curl_errno($ch)) {
        throw new Exception("Connection Error: " . curl_error($ch));
    }
    curl_close($ch);
    $jsonData = json_decode($response, true);
    if (!$jsonData || $jsonData["success"] === false) {
        $errorMessage = "错误信息：";
        if (!empty($jsonData["data"]) && is_array($jsonData["data"])) {
            foreach ($jsonData["data"] as $key => $value) {
                $errorMessage .= "<br>" . $key . "：" . $value[0];
            }
        } elseif (!empty($jsonData["message"])) {
            $errorMessage .= "<br>" . $jsonData["message"];
        }
        throw new Exception($errorMessage);
    }
    return $jsonData;
}
